#!/bin/bash

# Configure build variables.
BUILD_MODE=Debug
BUILD_ARCH=x64
GENERATOR_VER="Unix Makefiles"
ENABLE_TESTING=TRUE

CMAKE_GENERATOR="$GENERATOR_VER"

# Color configuration.
COLOR_OFF='\033[0m'
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'

PrintInfoMsg() {
    printf "$COLOR_GREEN >> $1 $COLOR_OFF\n"
}

PrintErrorMsg() {
    printf "$COLOR_RED >> $1 $COLOR_OFF\n"
}

CheckError() {
    if [ $? -ne 0 ]; then
        PrintErrorMsg "$1"
        exit 1
    fi
}

PrintInfoMsg "Creating a build directory..."
BUILD_DIR=../build/${GENERATOR_VER//[[:blank:]]/}-$BUILD_ARCH-$BUILD_MODE
mkdir -p $BUILD_DIR
CheckError "Failed to make the build directory."

cd $BUILD_DIR

PrintInfoMsg "[CMake] Generating the project..."
cmake \
    -G "$CMAKE_GENERATOR" \
    -DCMAKE_BUILD_TYPE=$BUILD_MODE \
    ../..
CheckError "[CMake] Failed to generate the project."

PrintInfoMsg "Project has been generated successfully!"
